---
# tasks file for update_users
#
        
- name: USER ACCOUNT | Check if the "{{ item }}" user exists
  shell: id -u "{{ item }}"
  register: user_exists
  ignore_errors: true

- debug: var=user_exists
 
- name: Get secrets from {{ platform }}
  uri:
    url: "{{ vault_url }}/v1/{{ platform }}/data/{{ application }}/{{ vnf }}/{{ item }}"
    body_format: json
    method: GET
    headers:
      X-Vault-Token: "s.ERc7VRhVOV7qt2dA2awN5Rgd"
    return_content: yes
    status_code: "200"
  register: user_pass

- debug: var=user_pass.json.data.data.password

- name: USER PASSWORDS | Update {{ item  }}  password
  user:
    name: "{{ item }}"
    password: "{{ user_pass.json.data.data.password |password_hash('sha512') }}"
    update_password: always
  when: user_exists.rc == 0

- name: Let us know user doesnt exist 
  shell: echo "User {{ item }} does not exist on this server"
  when: user_exists.rc != 0
